language: node_js
sudo: false
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_20fd811ec9c2_key -iv $encrypted_20fd811ec9c2_iv
  -in .travis/govuk_frontend_toolkit_npm_push.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git config --global user.name "GOV.UK Design System CI"
- git config --global user.email "design-system-pipeline@digital.cabinet-office.gov.uk"
- git remote add origin_ssh git@github.com:alphagov/govuk_frontend_toolkit_npm.git
install:
- echo "No dependencies to install"
script:
- "./publish.sh"
deploy:
  provider: npm
  email: govuk-dev@digital.cabinet-office.gov.uk
  api_key:
    secure: AJmAfaMVAXD0nAz8nGzIgNwxZckFHNkAnqQjqPBn/t6CaKiqTXuY6fzBKas1xMknzujMgvFqa16NSZJpwekiVWox0i6HycvU+gRP1oau8v7cNAca5jiLepO6HOhzNNlczJrC2G0EEkCUUptegHx8EJJTpH2r9xKC8Vunn0FCSfo=
  on:
    branch: master
